### ISSUE TITLE
[Bug] Apprentice disappears and doesn't come back when sleeping

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/ArcaneApprentices#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

At first the Apprentice died and showed message in text and could be regained by sleeping.

After several fights, the Apprentice disappears in the middle of a fight (was set to Follow Me), and does not return when sleeping.

![image](https://github.com/WinDanesz/ArcaneApprentices/assets/51968609/375bc573-b2d2-453f-8d07-ff19a1072852)

All configs for Arcane Apprentices are set to default.

### Expected behaviour

I expected the Arcane Apprentice to not disappear in the middle of a fight (no message in text).

If the Apprentice does disappear, I expected it to re-appear on sleeping.

As a last resort, it would be wonderful to have a keybind or something to regain Apprentices that are not respawning.

### Steps to reproduce

1. Join a Server
2. Gain a Apprentice
3. Get the Apprentice involved in numerous fights (leveling them to around level 10).
4. Apprentice suddenly disappears (see photo)
5. Try to regain Apprentice by sleeping in bed (no luck)
6. Look for some way to regain Apprentice (none apparent)

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.2.0

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
I replicated the issue with a second apprentice and was able to narrow it down to a ticking entity error (attached is the debug log showing the issue).

[apprentice debug log.txt](https://github.com/WinDanesz/ArcaneApprentices/files/14227726/apprentice.debug.log.txt)

My server config setting has "removeErroringEntities=true", in order to avoid past issues where the server gets stuck unable to load due to ticking enitites.

Likely, since this removes the Arcane Apprentice (detected as a ticking entity), then the mod still thinks the apprentice is alive and thus I am unable to revive him by sleeping in the bed.

Is it possible to have the Arcane Apprentices mod check to see if the Apprentice has been removed, and then have it returned by sleeping in bed (just as if the Apprentice is killed)?

**Comment by RulerOfEternity** [comment]
I've had an issue in one world where apprentices disappeared in general, I don't know what caused it, it could've been me travelling too far too fast, but I was unable to replicate it in a new world, not sure if this helps in any way at all but I wanted to mention it in case it does.

**Comment by KnightCa** [comment]
Set the server config setting has "removeErroringEntities=false", in order to get more crash logs with the Apprentice being a ticking enitity.

Here is the crash log:
[apprentice crash log2.txt](https://github.com/WinDanesz/ArcaneApprentices/files/14228597/apprentice.crash.log2.txt)

**Comment by KnightCa** [comment]
After restarting the crashed server (server config setting still "removeErroringEntities=false"), I get another crash log as soon as I rejoin the server and it loads my ticking Apprentice.

Here is the crash log:
[apprentice crash log3.txt](https://github.com/WinDanesz/ArcaneApprentices/files/14228606/apprentice.crash.log3.txt)

**Comment by KnightCa** [comment]
The latest version fixed the issue. It was apparently a result of the Apprentice being caught on fire, then trying to cast a resist fire, extinguish fire, blink spell when he doesn't have it as a available spell (thus becoming a ticking entity).

It now works great.
