### ISSUE TITLE
[Bug] Apprentice can't be regained/resurrected with Potion Core mod installed

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/ArcaneApprentices#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behavior

When Potion Core mod is installed, dead Apprentices die instantly when sleeping in a bed... but are still tracked as alive for the Arcane Apprentices mod and thus cannot be brought back to life by sleeping in the bed again.

The missing Apprentices are still being counted as Apprentices, and thus new Apprentices cannot be made to replace them.

### Expected behavior

I expected there be a way to recover a Apprentice if they disappear/die when Potion Core mod is installed.

### Steps to reproduce

1. Join a Server that has Potion Core and Arcane Apprentices mods installed.
3. Gain a Apprentice
4. Let Apprentice die
5. Try Sleeping on a bed, notice Apprentice appear briefly and instantly die once more.
6. Try Sleeping on a bed again and notice no resurrected Apprentice.
7. Try using a Totem of Undying on a Imbuement Altar and likewise no resurrected Apprentice.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.1.1

### Forge version

1.12.2-forge-14.23.5.2860

### Other mods

All installed mods: All latest versions
- Arcane Apprentices 1.1.1
- Electroblob Wizardry 4.3.12 (Arcane Apprentices required dependency)
- Wizardry Utils 1.2.0 (Arcane Apprentices required dependency)
- [Potion Core 1.9](https://www.curseforge.com/minecraft/mc-mods/potion-core)

**Comment by KnightCa** [comment]
Im unclear from the second setting message "Mutually exclusive with the APPRENTICES_CAN_BE_RESURRECTED setting.", if only one of these two settings can be set to true (perhaps something bad happens if they are both set to true). Thus I set the first to false and the second to true.

        # If true, died apprentices can be resurrected by using a Totem of Undying on an Imbuement Altar.
        B:"Apprentices Can Be Revived"=false

        # If true, died apprentices will just respawn at the player's spawnpoint the next time the player sleeps. Mutually exclusive with the APPRENTICES_CAN_BE_RESURRECTED setting.
        B:"Apprentices Respawn At Player Spawnpoint"=true

1. Started a brand single player new world
2. Gain the Healing discipline (book of fates)
3. Gain a Master wand, assign a Master Healing spell, and cast it (completing requirements for gaining a Apprentice)
4. Find a child in a village and give it a Wizards Handbook (gaining a Apprentice)
5. Set a Lectern and 2 beds nearby
6. Put a Magic Missile spellbook in Apprentice's hand and direct apprentice to Study it
7. Give Apprentice a Apprentice Wand with no spells.
8. Tell Apprentice to follow and begin fighting until Apprentice is killed (he casts Magic Missile during fights)
9. Go to bed at night where you found the Apprentice and sleep on one of the two beds
10. Apprentice appears briefly (message saying he is respawning) and I see him die instantly again (this time no message for his death).
11. At this point, sleeping in bed again will not return apprentice.

Player Dat file attached:
[playerdatfile.zip](https://github.com/WinDanesz/ArcaneApprentices/files/13724797/playerdatfile.zip)
![image](https://github.com/WinDanesz/ArcaneApprentices/assets/51968609/4b05836f-99b5-43da-8e01-44f22b2ebc05)

**Comment by KnightCa** [comment]
@WinDanesz Any chance to get the bug fixed for not being able to regain lost apprentices? Going to try the new version

**Comment by KnightCa** [comment]
I have narrowed down the issue to incompatibility with the Potion Core mod. I will update the issue to detail when it occurs.

**Comment by KnightCa** [comment]
Found the configuration in Potion Core that isnt compatible (changing it to false allows Apprentices to be resurrected):

    # Fixes your health resetting when changing dimensions/logging in if you
    # have a health boost potion effect or attribute modifier. Could possibly cause
    # issues with entity health, so if you see any issues, try disabling this. [default: true]
    B:"Fix Effects When Changing Dimensions"=true

If possible, can we setup Arcane Apprentices to not be effected by this being set to true (since it's a default)?

**Comment by WinDanesz** [comment]
Great finding, I'll see what can be done about it

**Comment by brisingraerowing** [comment]
Honestly, PotionCore's implementation of that is very buggy and has caused issues with other mods in the past.

**Comment by WinDanesz** [comment]
I could set it to false from my mod when the game start, but that might surprise some pack makers if they depend on it. But in all honesty if it works so bad I don't think anyone would miss it. Thoughts?

**Comment by KnightCa** [comment]
If it’s possible to set the Potion Core config for that feature to false when starting Arcane Apprentices automatically, that would solve this issue.The main desire is to have it happen automatically rather than ask the players/modpack makers to set it manually, so the Apprentuces just work correctly :)On Feb 2, 2024, at 2:50 AM, WinDanesz ***@***.***> wrote:﻿
I could set it to false from my mod when the game start, but that might surprise some pack makers if they depend on it. But in all honesty if it works so bad I don't think anyone would miss it. Thoughts?

**Comment by KnightCa** [comment]
Fixed in latest version.
